### ISSUE TITLE
use cibuildwheel to build all the wheels

### ISSUE THREAD

**Issue by fgregg** [dmuellner/fastcluster#26]
Hi Daniel,

Hope all is well with you! I've been having a great experience with [cibuildwheel](https://github.com/pypa/cibuildwheel), which is an official project of the Python Packaging Authority. They've made it a lot easier to use CI to build all the different flavors of wheels.

Would you be open to a PR that sets this up?  This would use github actions instead of travis for the CI?

**Comment by dmuellner** [comment]
Hi Forest,

I am definitely open to suggestions. The process of building wheels in a CI service has been the most time-consuming part of maintaining the package. The code and documentation updates have been tiny in the past few years but every new release needed new experimentation with the CI configs. If GitHub actions turns out to be stable, I am open to switch. I might be able to explore GitHub actions a bit in the next few days. If you already have configs to build wheels for Windows, macOS, and ARM Linux (maybe from a similar package), let me know.

Cheers, Daniel

**Comment by fgregg** [comment]
yes, 

https://github.com/dedupeio/hcluster/blob/59bc901288bac93a5f61bbe5bab2033b117d00e1/.github/workflows/pythonpackage.yml#L43-L77

by default, it builds wheels for these platforms: windows 32bit, windows 64bit, manylinux x86_64, mac intel. I've set a few config options so it also builds for mac silicon, and 646i architectures. Right now it builds for python3.6-3.10 + pypy.

the great thing is as new vesions of python get released then we shouldn't have to update the CI config.

**Comment by fgregg** [comment]
closed by #29
